name: Run flake checks

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install nix ❄️
        uses: cachix/install-nix-action@v16

      - name: Run checks ✅
        run: nix flake check
