name: Deploy Documentation to netlify

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "netlify"
  cancel-in-progress: true

jobs:
  build-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Install nix ❄️
        uses: cachix/install-nix-action@v16
      - name: Build 🛠️
        id: build
        run: |
          export SYSTEM=$(nix eval --impure --raw --expr "builtins.currentSystem")
          echo "::set-output name=system::$SYSTEM"
          nix build ".#docs.${SYSTEM}.manual.html" -vL
          echo "::set-output name=html::$(readlink result)/share/doc/nix-basement"
    - name: Publish 🗞
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=${{ steps.build.outputs.html }}
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
